spring:
  #数据库(mysql8.0版本)配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  #配置thymeleaf
  thymeleaf:
    #应用于模板的模板模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码
    encoding: UTF-8
    #在构建URL时预先查看名称的前缀
    prefix: classpath:/templates/
    #构建URL时附加到查看名称的后缀
    suffix: .html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false


#mybatis配置
mybatis:
  #配置别名
  type-aliases-package: com.yu.domain
  #加载Mybatis映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
